- name: rpm-ostree
  hosts: '{{ hosts | default("all") }}'
  sudo: yes
  tasks:
    - copy: src=rpm-ostree-containers dest=/root/flannel_etcd_containerized/

    - file: path=/var/runc
      args:
        state: directory

    - name: create ostree repo
      command: ostree --repo=/var/runc/ostree-repo init --mode=bare
      args:
        creates: /var/runc/ostree-repo

    - name: create etcd container
      command: rpm-ostree --repo=/var/runc/ostree-repo compose tree etcd.json
      args:
        chdir: /root/flannel_etcd_containerized/rpm-ostree-containers

    - name: create flannel container
      command: rpm-ostree --repo=/var/runc/ostree-repo compose tree flannel.json
      args:
        chdir: /root/flannel_etcd_containerized/rpm-ostree-containers

    - file: path=/var/runc/etcd/rootfs
      args:
        state: directory
    - name: export etcd-container
      command: ostree checkout --repo=/var/runc/ostree-repo fedora-atomic/f23/x86_64/etcd /var/runc/etcd/rootfs
      args:
        creates: /var/runc/etcd/rootfs

    - file: path=/var/runc/flannel/rootfs
      args:
        state: directory
    - name: export flannel-container
      command: ostree checkout --repo=/var/runc/ostree-repo fedora-atomic/f23/x86_64/flannel /var/runc/flannel/rootfs
      args:
        creates: /var/runc/flannel/rootfs

    - include: start-services.yml
